### ISSUE TITLE
TransIt 是否需要添加发音功能

### ISSUE THREAD

**Issue by greatghoul** [GDG-Xian/crx-transit#17]
之前有用户提出，希望可以增加自动发音功能，这个功能做起来虽然不麻烦，但希望和大家讨论下，这个功能是否有必要。

因为目前的翻译结果中已经提供了音标，对于发音，已经有了一部分辅助，是否还需要像其它辞典一样，提供英式和美式的发音，如果后面添加更多语种，发音就会从一个小功能变成一个大功能。因为适配不同的语言，也是比较麻烦的事，而且百度翻译和有道似乎也都没有提供获取发音的接口。

基于以上的考虑，我个人觉得提供发音这个功能不是特别必要，但既然有用户提出来，我也想听听大家的意见。

**Comment by qwIvan** [comment]
我一直在用ChaZD https://github.com/ververcpp/ChaZD。
两者对比，transit的优势是可以按住shirt键查询链接中的单词。
ChaZD是有发音功能，提供了英式和美式发音。

**Comment by jerry011235** [comment]
个人觉得还是像划词翻译一样，做一个发音的选项比较好。需要就开，不需要就关。
