### ISSUE TITLE
更方便的链接划词翻译

### ISSUE THREAD

**Issue by greatghoul** [GDG-Xian/crx-transit#24]
通过左右移动鼠标两次来临时激活链接划词模式而不使用其它辅助按键。

shift / ctrl / alt 等辅助键都有其保留的功能，如果 transit 占用，会对浏览器的正常操作造成影响。

**Comment by magicalwz** [comment]
表示caps lock比较难用，建议下次更新时给个选项自己选择以何种方式取词。

**Comment by greatghoul** [comment]
嗯，确实个人喜欢不同，谢谢你的建议，我下个版本会加入，此前请先忍耐。
