### ISSUE TITLE
切换到有道词典获取不到翻译

### ISSUE THREAD

**Issue by liul85** [GDG-Xian/crx-transit#33]
切换到有道词典不work啊，建哥。。。

**Comment by greatghoul** [comment]
有道的服务器有段时间抽风来着，你过段时间再试应该就 ok 了，如果还不行，可以把扩展背景页的错误给我看。

![image](https://cloud.githubusercontent.com/assets/208966/6619554/047c5e16-c906-11e4-8cf9-8d180bffc9ae.png)
