### ISSUE TITLE
控制台报错

### ISSUE THREAD

**Issue by Suxiaogang** [GDG-Xian/crx-transit#34]
Resources must be listed in the web_accessible_resources manifest key in order to be loaded by pages outside the extension.

**Comment by greatghoul** [comment]
哎哟我去，从来没有在 contentscript 中载入过图片呀，怎么会有这种错误，能够截图或者帖上完整信息吗，我要知道是哪个资源访问限制。

**Comment by Suxiaogang** [comment]
![image](https://cloud.githubusercontent.com/assets/1567518/6639894/88d928f6-c9ce-11e4-8b68-3af5fa24c738.png)

我装的插件比较多,但确定是这个的.

**Comment by greatghoul** [comment]
非常感谢你的反馈，原来是 source map 的缘故，以前其实我已经处理过这个错误了，不过因为最近用 bower, gulp coffee 还有 sass 把 transit 重写了，所以又把这个 bug 挖出来了，我会尽快修改的。

**Comment by Suxiaogang** [comment]
不客气,我也是西安的,也倒腾过几个Chrome扩展,有机会可以交流下~

**Comment by greatghoul** [comment]
欢迎交流。

**Comment by kingheaven** [comment]
关注我们GDG西安社区吧: http://gdgxian.org/  

----  
Best Regards,
David XIE
Founder of ScriptFan technology community - http://scriptfan.com (http://scriptfan.com/)
Manager of Xi'an GDG (Google Developer Group)
http://about.me/davidx

-----------------
Everything happens for a reason. Attitude determines everything!

**Comment by Suxiaogang** [comment]
@kingheaven 嘿嘿,参加过一次活动
业余时间也写过几个GoogleChrome插件:

https://chrome.google.com/webstore/detail/%E8%B1%86%E7%93%A3%2B%E7%99%BE%E5%BA%A6%E7%BD%91%E7%9B%98/phnkdkohjfmfbokjogjfbfmcfocfkebk

https://chrome.google.com/webstore/detail/%E6%96%B0%E6%B5%AA%E5%BE%AE%E5%8D%9A%E5%9B%BE%E5%BA%8A/fdfdnfpdplfbbnemmmoklbfjbhecpnhf

https://chrome.google.com/webstore/detail/smooth-scroll/ghghlbdebkoefdmbfjkicnehjgkmcamf

**Comment by greatghoul** [comment]
好赞的扩展，是开源的吗，求参加交流。

**Comment by Suxiaogang** [comment]
都是啊 在我的repo里,写的比较渣,欢迎提一些好的建议.
