### ISSUE TITLE
双击CapsLock 第一次划词ok 第二次就失效了 再怎么按CapsLock 都无效

### ISSUE THREAD

**Issue by hnboy2005** [GDG-Xian/crx-transit#36]

**Comment by hnboy2005** [comment]
比如这个网页 好像就失效
http://www.cnbc.com/id/102541217?__source=yahoo%7Cfinance%7Cheadline%7Cheadline%7Cstory&par=yahoo&doc=102541217

**Comment by greatghoul** [comment]
感谢反馈，你提及的这个网页，我试验只在右侧 MORE FROM CNBC 那块的链接上面失效了，不过 Caps Lock 似乎并不是一个好的快捷键，我需要寻找其它可行的方案，之前有用户提到希望能够定制激活链接划词的快捷键。这样应该能够行的通，大家喜好不同。
