### ISSUE TITLE
wikia的网站不能取词、

### ISSUE THREAD

**Issue by magicalwz** [GDG-Xian/crx-transit#37]
wikia的网页选词后都必须点击图标才能看解释。希望能够修复。
update:有时可以有时不行，不知何故。大部分时间都不行。已经翻墙，确定不是网页载入不完整的问题。

**Comment by greatghoul** [comment]
感谢反馈，我尽快处理。

**Comment by greatghoul** [comment]
该网站已经支持取词了。
