### ISSUE TITLE
新版本的开发版扩展木有extension文件夹

### ISSUE THREAD

**Issue by delphi-2015** [GDG-Xian/crx-transit#38]
最新版的如何安装开发版扩展，步骤提示“选择源文件中的 extension 文件夹并打开 ”，但是没有此文件夹啊

**Comment by greatghoul** [comment]
新版本正在重构，将使用新的方式来构建扩展程序，请耐心再等几天。或者你可以先使用老版本。

:D

**Comment by greatghoul** [comment]
![](http://greatghoul.b0.upaiyun.com/1512/Vde1ocTozhpDT.png)

以后扩展发布版本时会上传一个压缩包到 releases 中，直接下载解压然后载入就可以用了。
