### ISSUE TITLE
弹出层在 http://www.example.com/ 这个网站会样式错乱

### ISSUE THREAD

**Issue by Suxiaogang** [GDG-Xian/crx-transit#44]
不是举例子啊,是真的http://www.example.com/ 这个网站... ... 偶然看到的

**Comment by david-xie** [comment]
确实是

不过话说你怎么看到这个网站的...

**Comment by david-xie** [comment]
@greatghoul 已经找到问题的原因了. 这个www.example.com里的css是指定给元素的, 比如div, 没有用任何id或者class....

**Comment by Suxiaogang** [comment]
@david-xie 偶然点进去的,然后想翻译一下illustrative这个单词来着...
另外log那个issues(#42)也看看吧,我的console也被各种调试语句和log污染了

**Comment by david-xie** [comment]
@Suxiaogang 好得, 我看看. 减少一些log的输出应该就没问题了
