### ISSUE TITLE
设置主题或者皮肤？

### ISSUE THREAD

**Issue by 775405984** [GDG-Xian/crx-transit#46]
现在transit是用过的最好的划词翻译扩展，但是绿底白字我觉得不太好看，能不能增加一个选项，可以更换皮肤的，白底黑字，就跟Google Translate 以及github界面一样。

谢谢～

**Comment by greatghoul** [comment]
这个其实已经在计划中了，不过最近有些忙，一直没有更新，感谢你的反馈。
