### ISSUE TITLE
添加将单词保存到印象笔记的功能

### ISSUE THREAD

**Issue by 775405984** [GDG-Xian/crx-transit#50]
弹窗里弄个按钮什么的，谢谢。

**Comment by Tyraan** [comment]
同意 ，最好能出一个生词本  功能，保存单词。

**Comment by greatghoul** [comment]
我有考虑过这个功能。

提供一个查看历史查询记录的地方。至于数据同步，也考虑过多种实现。

- Google Sheet
- Evernote 笔记
- 幕布
- 扇贝单词本

**Comment by greatghoul** [comment]
https://github.com/greatghoul/smooth-translator/issues/2
