### ISSUE TITLE
1.5版，windows下比如访问百度，输入框按capslock，页面布局会乱 

### ISSUE THREAD

**Issue by billzhuang** [GDG-Xian/crx-transit#56]
已一个个排除，确认是TransIt的问题，三台电脑均有此问题。  谢谢

**Comment by david-xie** [comment]
@billzhuang 能帮忙截个图吗? 我手边暂时没有windows...

**Comment by greatghoul** [comment]
![](http://greatghoul.b0.upaiyun.com/1603/61X2Qm_i_T5ld.png)

应该不止 windows 上了，osx 下面也是。 @billzhuang ，感谢你的反馈，我会尽快修复。

**Comment by greatghoul** [comment]
@billzhuang 我已经尝试修复了这个问题，你可以等商店自动更新，或者安装开发版。

https://github.com/GDG-Xian/crx-transit/releases/tag/V1.5.1

**Comment by billzhuang** [comment]
已更新，确认已修复，谢谢啦
