### ISSUE TITLE
划词后页面自动朗读单词和释义

### ISSUE THREAD

**Issue by greatghoul** [GDG-Xian/crx-transit#61]
添加一个选项，让用户可以在划词后页面不显示翻译结果，而是自动通过语音朗读出来发音和释义。

发音可以抓取国内流行翻译网站的发音，释议可以使用百度 tts api.

一些可能的定制：
- 只朗读音标
- 只朗读释义
- 朗读音标和释义
- 释义只朗读第一条

**Comment by lonely12Wolf** [comment]
上档次
