### ISSUE TITLE
插件里的有道翻译链接失败

### ISSUE THREAD

**Issue by Heisosmith** [GDG-Xian/crx-transit#65]
这是GoAgent的报错信息：GAE GET http://fanyi.youdao.com/openapi?path=frequent-error
bing翻译选项,输入查词后，没有出现翻译结果界面。GAE GET http://cn.bing.com/dict/search?q=hello
百度翻译选项正常。

**Comment by Heisosmith** [comment]
重启后，有道可以用了。
bing翻译，不挂proxy可以显示出结果。

**Comment by greatghoul** [comment]
![image](https://cloud.githubusercontent.com/assets/208966/17240098/aa6f9522-559b-11e6-9ec4-9f2c0b50c0a9.png)

@Heisosmith 是否能够提供一必应的请求结果，挂代理后，可能返回的翻译页面的结构发生了变化，但插件没有能够适配到。

关于有道的 API, 现在还使用的 API KEY，会有限额，我会在下个版本替换成直接抓取页面的方式。
