### ISSUE TITLE
多次划词之后无法关闭

### ISSUE THREAD

**Issue by xiaok** [GDG-Xian/crx-transit#66]
![image](https://cloud.githubusercontent.com/assets/734528/18044987/0a602fee-6e03-11e6-9c5d-7d396c74ec59.png)
点击x后，报错

**Comment by greatghoul** [comment]
收到。

**Comment by greatghoul** [comment]
https://github.com/GDG-Xian/crx-transit/releases/tag/V1.6.1

已解决
