### ISSUE TITLE
源代码版本的插件无法安装

### ISSUE THREAD

**Issue by yellowbee686** [GDG-Xian/crx-transit#67]
看到西安的乡党做了这个划词翻译扩展，非常开心，我fork了一份源码，想在本地安装，但错误非常多... 比如html中引用的是css文件，但其实提供的是scss文件；比如import的sprite.scss，但提供的文件是_sprite.scss；比如取sprite.svg的目录层级不对... 求问是不是我安装姿势不对... npm install之后需要执行哪些步骤？

**Comment by yellowbee686** [comment]
作为一个纯粹的前端小白...现在搞明白了，需要先npm install 再grunt即可成功自动化构建项目... 按照步骤一步步来，在windows下构建时还可能遇到SSL证书的问题导致无法gem install sass，参考https://github.com/ruby-china/rubygems-mirror/wiki 可以解决

**Comment by greatghoul** [comment]
```
  grunt.registerTask('build', ['jshint', 'browserify', 'sass', 'copy']);
  grunt.registerTask('dist', ['build', 'uglify', 'compress'])
  grunt.registerTask('default', ['build', 'watch'])
```

有这么几个命令

```
grunt build
grunt 
grunt dis
```

**Comment by greatghoul** [comment]
最近在去除掉 scss 的依赖，使用纯静态的的文件进行维护，所以如果有兴趣可以再等等。
如果只是想安装源代码的版本，可以去 Release 里面去下载

https://github.com/GDG-Xian/crx-transit/releases
