### ISSUE TITLE
Translt 有道翻译下出现异常

### ISSUE THREAD

**Issue by AnglusWang** [GDG-Xian/crx-transit#68]
Translt 偏好设置为：使用有道翻译，经常出现翻译不了的情况，停留在正在翻译界面，并且一段时间后弹窗不会消失。

**Comment by greatghoul** [comment]
现在有道翻译使用的是 API，我的 key 有调用次数的限制，所以如果一个小时内，调用的次数超过时限了，就会出现这种情况。

虽然可以做一个自己设置 key 的版本，但对用户来说，并不是很友好，用户没有必要为了使用一个翻译软件，而去申请一个 key，所以打算使用直接抓取页面的做法。

请耐心等待。

**Comment by david30xie** [comment]
@greatghoul homebrew也有类似的问题, 过多的调用github api以后, 会出现用户无法使用的情况. 它的解决办法是, 给用户使用自己的key的选项.
就变成了, 你可以不做任何设置用homebrew的key, 也可以设置一下用自己的key.

**Comment by greatghoul** [comment]
@david30xie 有这样的解法，但只是对开发者友好的，对于非开发者来说，绝对理解不了这个 key 是做什么用的。

比如我用一个查天气的软件，查不了了，还得我自己去申请一个天气 API 的 key，我绝对是不干的。

我已经用抓取页面的方式解决了，还有另一个 bug 解决后会一起发布。

**Comment by AnglusWang** [comment]
原来如此，期待新版本的发布，赞一个

**Comment by greatghoul** [comment]
@AnglusWang 已更新，你可以等自动更新，也可直接下载开发版

https://github.com/GDG-Xian/crx-transit/releases/tag/V1.6.1
