### ISSUE TITLE
在国内谷歌翻译模式下，始终默认翻译结果为中文

### ISSUE THREAD

**Issue by mrcodehang** [GDG-Xian/crx-transit#69]
在遇到中文的时候， 想检索他的英文意思， 结果翻译出来的也是中文。 还要手动去调整才能修复。 能否修复这个bug。 难道这个bug是谷歌翻译的问题？

**Comment by greatghoul** [comment]
@mrcodehang 这的确是个 bug，我对汉译英的确没有做什么特殊的处理。

**Comment by greatghoul** [comment]
你用的是哪个翻译服务？TransIt 目前并没有提供谷歌翻译。

**Comment by mrcodehang** [comment]
划词翻译。 不是可以选择调用google api嘛

**Comment by greatghoul** [comment]
并不是，目前只支持有道，百度和必应。

**Comment by mrcodehang** [comment]
额 是不是进错地方了。 能不能增加支持google。 感觉谷歌的翻译现在真心强大

**Comment by greatghoul** [comment]
@mrcodehang 我想你可能进错地方了。

https://github.com/ververcpp/ChaZD

你用的是不是这个，印象中这个扩展支持挺多翻译服务的，我的扩展进度慢些。

**Comment by greatghoul** [comment]
暂时没有打算支持 Google 翻译，有两点原因：

1. Google 翻译的 API 是付费的，我没有办法通过调用 API 来实现 Google 翻译
2. 虽然可以用抓取页面的方法来取得翻译结果，但我是西安 GDG 的组织者，与 Google 有一定的利益关系，不太合适走这种路子。

**Comment by mrcodehang** [comment]
噢， 那真令人感到遗憾
