### ISSUE TITLE
你好!

### ISSUE THREAD

**Issue by Jefrl** [GDG-Xian/crx-transit#70]
你好! 
      关于安装想问下 "步骤3.选择源文件中的 extension 文件夹并打开"  发现clone 的文件夹中没有 Extension 文件夹, 如果选择最外层的文件夹crx-transit, 添加不了; 可能我哪里操作不当, 求指导下

**Comment by greatghoul** [comment]
这个 wiki 写得有些过时了，现在我是把包都发到 releases 里面了，你可以从里面下载那个 Transit 版本号 zip 包

**Comment by Jefrl** [comment]
谢谢!
