### ISSUE TITLE
没有自己的样式？一直是跟着注入的网站样式走的

### ISSUE THREAD

**Issue by suxiaogang** [GDG-Xian/crx-transit#74]
这会导致一些奇怪的字体和文字颜色出现

似乎和 #46 这个是类似的问题，但又不是完全一样的需求。

**Comment by greatghoul** [comment]
有的，但在有一些网站上会失效。方便的话，提供一下失效的网站，方便完善兼容性。

**Comment by suxiaogang** [comment]
![image](https://user-images.githubusercontent.com/1567518/28067189-c8fe5e22-6672-11e7-880c-e9efca1273d3.png)

https://stormpath.com/blog/where-to-store-your-jwts-cookies-vs-html5-web-storage

**Comment by suxiaogang** [comment]
还有一些阿拉伯语？网站，翻译结果的font-family感觉也很奇怪。以后我碰到了就粘贴到这里。
