### ISSUE TITLE
【建议】增加 Firefox 适配

### ISSUE THREAD

**Issue by 775405984** [GDG-Xian/crx-transit#76]
Firefox 57 发布在即，试用了测试版和开发版，感觉和记忆中的Firefox大相径庭。

一个字： **快**！

新的Firefox开启了多线程，引擎也换了，这里还增加了WebExtension。

所以，希望@greatghoul 可以适配 Firefox 版本。

谢谢！

另：如何编写一个WEB插件   https://www.jfh.com/jfperiodical/article/1169

**Comment by greatghoul** [comment]
这个项目没有基于扩展工具包构建，所以目前这个版本要支持 Firefox 比较麻烦，不过我有计划把扩展迁移到一个成熟的打包工具，会自动适配各浏览器的兼容性，到时候会支持 Firefox.

另外，这个扩展我已经终止维护了，新的扩展在这里。
https://github.com/greatghoul/smooth-translator

主要的一些改变：

- 移除有道之外的翻译服务
- 不再提供在鼠标划词附近显示翻译结果的选项
- 可以针对不同的域名 启用 / 禁用划词翻译

做出这一改变的主要原因是我想把它做成[最初我想做的样子](https://github.com/GDG-Xian/crx-transit/issues/72)（不干扰阅读的翻译扩展），尽量减少不必要的定制。

如果你想寻找一款功能全面，全能定制的划词翻译扩展，推荐
https://github.com/Selection-Translator/crx-selection-translate

开发非常活跃，扩展也非常优秀。

感谢你对这个扩展的关注。

**Comment by 775405984** [comment]
@greatghoul SmoothTranslator 的主页和官方扩展页面显示的都是 TransIt，是因为没有发布吗？大约什么时候能发布呢？

**Comment by greatghoul** [comment]
还没有发，大概得两周左右吧，我还在重写代码。
