### ISSUE TITLE
最近在 Chrome 中已经不好用了

### ISSUE THREAD

**Issue by shangleixun** [GDG-Xian/crx-transit#78]
我最喜欢使用的必应，现在已经不能用了。希望开发者及时更新一下子。多谢。

**Comment by greatghoul** [comment]
发现另一个翻译扩展也遇到了类似的问题。
https://github.com/Selection-Translator/crx-selection-translate/issues/250

**Comment by greatghoul** [comment]
我发现翻译单词的服务依然可用，但是翻译整句的出了问题。

**Comment by greatghoul** [comment]
更新了，修了必应和百度的问题。1.6.3 稍后商店应该会有推送。

你也可以自己下载开发版安装。
https://github.com/GDG-Xian/crx-transit/releases/tag/V1.6.3

**Comment by greatghoul** [comment]
@shangleixun 

我不知道是不是你网络的问题，我在我在机器上没有感觉怎么慢呀。
![image](https://user-images.githubusercontent.com/208966/34166964-5437f738-e51b-11e7-9274-4c0d72977181.png)

**Comment by shangleixun** [comment]
谢谢，目前使用正常，谢谢开发者热心回复和更新！
