### ISSUE TITLE
翻译结果显示在划词文本附近时，弹出的位置有误

### ISSUE THREAD

**Issue by greatghoul** [GDG-Xian/crx-transit#79]
划词翻译结果显示在文本附近时，弹出翻译结果的位置有误，跑到了页面最底端（页面有滚动条时）
https://www.google.com/about/software-principles.html

![image](https://user-images.githubusercontent.com/208966/34168038-5fb08e42-e51e-11e7-9006-f7b6be970a06.png)

**Comment by harrynull** [comment]
补充一下，我发现在很多网页中，只要滚动条向下滚了，弹出的位置就不正确，是在滚动条在最上时候的那个位置。例如谷歌的搜索结果页。这导致如果滚动条滚动超过了一页，翻译结果就完全不显示了，很影响使用。

**Comment by greatghoul** [comment]
在 1.6.4 中解决了，不过这个版本增加了 webRequest 权限，审核可能会需要一些时间。

可以在这里下载开发版尝鲜
https://github.com/GDG-Xian/crx-transit/releases/tag/V1.6.4
