### ISSUE TITLE
能否增加背景色设定，尤其是加入透明背景色

### ISSUE THREAD

**Issue by futandrew** [GDG-Xian/crx-transit#83]
现在的功能以及很完全很完整了，首先很感谢！其次是否能够加入一个更改背景色，透明度等更多个性化的设置？十分感谢！

**Comment by greatghoul** [comment]
这个扩展已经不再维护了，所以不会增加新功能，如果你有修改背景色的需求，我可以给你一个你喜欢的配色的开发版（就是个 zip 包）

这个扩展的[精简版](https://github.com/greatghoul/smooth-translator)倒是有修改背景色的功能，不过还在开发中（其实最近也没有什么时候改）

**Comment by futandrew** [comment]
那很好，谢谢🙏。另外期待出更好的插件！

**Comment by futandrew** [comment]
请问我在哪里下载呢？

**Comment by greatghoul** [comment]
> 请问我在哪里下载呢？

你是指开发版吗？

https://codepen.io/anon/pen/WLbQMg

我需要知道你喜好的配色，如果你懂 css，可以在这里自己改一下，发给我，我打包给你扩展。

或者你如果懂前端开发，也可以下载扩展，修改这个文件，然后自己编译，样式在这个文件中。

    ⁨src⁩/⁨css⁩/⁨includes⁩/_transit_result.scss

**Comment by futandrew** [comment]
太感谢。因为我不是很懂这些东西。。所以麻烦你了！
我希望背景是透明色，字是黑色。就这些要求。实在麻烦您了！
另外我还是加油学习哈哈哈。

**Comment by futandrew** [comment]
https://codepen.io/futandrew/pen/VqYyBd 
大致长这样。。谢谢

**Comment by greatghoul** [comment]
👌收到，我稍后发给你。

**Comment by futandrew** [comment]
谢谢。若是能把那个底部阴影去掉就更完美了！十分感谢

**Comment by greatghoul** [comment]
哈哈，自己的工程，自己都跑不起来了，给我多一些时间 😅

**Comment by greatghoul** [comment]
https://www.jianguoyun.com/p/DbvM9ZMQio0BGJSkjQE

我从之前打包过的版本里面修改了 css，试了下，没有什么问题。

**Comment by futandrew** [comment]
成功了，十分感谢！！
